server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Malamut73/springcloud-config.git
#          uri: https://github.com/kwazart/springcloud-config.git
          search-paths: step04
#          search-paths: springleveltwo/lesson05/step04
          clone-on-start: true
  application:
    name: config_server

logging:
  level:
    org.springframework.cloud: DEBUG